{% set name = "duckdb" %}
{% set version = "0.2.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cwida/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5ed30486f7f9877f5e5d2fd7047347b86fa9ca105e1ed41e53e1fcb4b3f7bc0c
  patches:
    # - 487.patch

build:
  number: 1
  skip: true  # [win]
  script: cd tools/pythonpkg && SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} $PREFIX/bin/python setup.py install

requirements:
  build:
    - cmake
    - ninja
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11 >=2.4
    - python
    - pip
    - setuptools_scm
    - numpy
    - pandas
    - arrow-cpp >=1.0.1
    - pyarrow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - arrow-cpp
    - pyarrow

test:
  imports:
    - duckdb
  requires:
    - pip
    - pytest
  source_files:
    - tools/pythonpkg/tests
  commands:
    - pip check
    - pytest tools/pythonpkg/tests

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://www.duckdb.org/docs/current/index.html
  dev_url: https://github.com/cwida/duckdb

extra:
  recipe-maintainers:
    - xhochy
    - mariusvniekerk
